### ISSUE TITLE
{Request] Basalt Generator Modifier

### ISSUE THREAD

**Issue by KMFrench1** [null2264/CobbleGen#1]
Can you add custom methods of generation that uses the lava and blue ice method. But lets me replace the soul soil with another block to generate a different block.
For example: I want to have the player need lava flowing on top red sand and next to blue ice to generate a blackstone block.

**Comment by null2264** [comment]
Not sure if that's possible, that feature is in my TODO list for awhile... couldn't figure out how to do it yet tho
