### ISSUE TITLE
Broken Basalt?

### ISSUE THREAD

**Issue by DemonSlayer112** [null2264/CobbleGen#13]
Here's the config im using, pretty much nothing in terms of modifying basalt generators: [cobblegen.zip](https://github.com/null2264/CobbleGen/files/11047718/cobblegen.zip)

And the issue here is it removes the need for soulsoil! This feels like a bug right?
Assume since we cant modify the soulsoil or blue ice it shouldnt negate soulsoil ?
![image](https://user-images.githubusercontent.com/70122500/227123506-cec41445-39af-4be7-8a79-38e3b96b056a.png)

Basing this on this discussion: https://github.com/null2264/CobbleGen/discussions/11

**Comment by null2264** [comment]
Try this build:

[1.19.3+](https://github.com/null2264/CobbleGen/files/11051176/1.19.3.zip)
[1.18-1.19.2](https://github.com/null2264/CobbleGen/files/11051178/1.18.zip)

**Comment by DemonSlayer112** [comment]
That works! :D
And it doesnt effect the other custom gens defined!
