### ISSUE TITLE
Support for JEI if possible

### ISSUE THREAD

**Issue by Nezzzer** [null2264/CobbleGen#17]
There's a Mod on the forge loader which is basically the same idea, yet it has one advantage, the JEI view, and I was wondering if it would be possible to add that to this Mod.

**Comment by null2264** [comment]
It is a planned feature, I'm not familiar with JEI plugin API, that's why I haven't added it. I'll take a look at it again later today...

**Comment by null2264** [comment]
The basics has been implemented if you need it:
[JEI Build](https://github.com/null2264/CobbleGen/files/11280457/Artifacts.zip)

It's only missing some polishing and additional info like Y-level limit, and dimension.

**Comment by Nezzzer** [comment]
nice, thanks for the effort :D
