### ISSUE TITLE
Replaced cobblegen v2.1b57-BETA with cobblegen v3.2+3-BETA. Server boots then crashes as people join.

### ISSUE THREAD

**Issue by erikd8** [null2264/CobbleGen#24]
[crash-2023-04-26_17.06.26-server.txt](https://github.com/null2264/CobbleGen/files/11345903/crash-2023-04-26_17.06.26-server.txt)

Title explains the situation fairly well. Replaced with latest update of cobblegen, server was able to start successfully though when any player joined it would lead to a crash.

This is on a pre-existing world, initially assumed it might be due to cobblegens from later version existing in the world when they are no longer supported? Unsure.

**Comment by null2264** [comment]
Try this build:
[cobblegen-fix.zip](https://github.com/null2264/CobbleGen/files/11348792/cobblegen-fix.zip)

**Comment by null2264** [comment]
Should be fixed in 3.2.1:
https://modrinth.com/mod/cobblegen/version/3.2.1+4-BETA
