### ISSUE TITLE
Config not synced. 

### ISSUE THREAD

**Issue by NarwhalAndMe** [null2264/CobbleGen#33]
I am not sure to what exactly causes this, but it seems as if the config is hard coded as when I change the config the changes do not take affect in my single player world.

**Comment by null2264** [comment]
The config only reverted back to default when the user config is not valid, try checking the log... it should say it failed to retrieve config or something.

**Comment by NarwhalAndMe** [comment]
There is nothing like that in the log. I can send the config file to have you look over it cause I am not well versed in JSON if you'd like.

**Comment by null2264** [comment]
Yeah, that'd be great... Also, could you send the log so I can get more context?

**Comment by NarwhalAndMe** [comment]
`{
	"cobbleGen": [
		{
			"id": "minecraft:emerald_ore",
			"weight": 2.0
		},
		{
			"id": "minecraft:diamond_ore",
			"weight": 5.0
		},
		{
			"id": "minecraft:lapis_ore",
			"weight": 8.0
		},
		{
			"id": "minecraft:gold_ore",
			"weight": 10.0
		},
		{
			"id": "minecraft:iron_ore",
			"weight": 15.0
		},
		{
			"id": "minecraft:coal_ore",
			"weight": 20.0
		},
		{
			"id": "minecraft:cobblestone",
			"weight": 20.0
		},
		{
			"id": "minecraft:cobbled_deepslate",
			"weight": 20.0
		}
	]
	"stoneGen": [
		{
			"id": "minecraft:stone",
			"weight": 40.0
		},
		{
			"id": "minecraft:diorite",
			"weight": 20.0
		},
		{
			"id": "minecraft:andesite",
			"weight": 20.0
		},
		{
			"id": "minecraft:granite",
			"weight": 20.0
		}
	]
	"basaltGen": [
		{
			"id": "minecraft:basalt",
			"weight": 100.0
		}
	]
}`

and then the logs are here https://mclo.gs/MabP656

Thanks!

(apologies for the bad formatting i am terribly new to github and dont know how to do codeblocks!)

**Comment by null2264** [comment]
The mod seems to detect the config as invalid:
`blue.endless.jankson.api.SyntaxError: Found unexpected character ',' while looking for the colon (':') between a key and a value in an object`

But the config you provided seems to be valid. Could you send me the config again as a file instead? You can just drag and drop the file to the comment box or you can upload it to [wormhole](https://wormhole.app/)

**Comment by NarwhalAndMe** [comment]
will do, link is here! https://wormhole.app/ppjB4#tzuhwD3FhWj0BPDZE44ZnQ

i went to the website and put the file in and got hella disoriented so my head hurts haha, caught off guard with the effects

**Comment by null2264** [comment]
Well, that's strange, it works for me... maybe try redownloading the mod?

![image](https://github.com/null2264/CobbleGen/assets/46041660/99ba32d0-cad8-45da-b95b-3d75f3788d48)

**Comment by NarwhalAndMe** [comment]
on it boss

**Comment by NarwhalAndMe** [comment]
redownloading worked... thats very strange. thanks!

**Comment by null2264** [comment]
Probably corrupted somehow, but glad that helps!
