### ISSUE TITLE
Failed to initiate setupDisplay REI

### ISSUE THREAD

**Issue by Disketaa** [null2264/CobbleGen#34]
Last fabric 1.20 version, v5.0.0 mod ver, REI mod.

![image](https://github.com/null2264/CobbleGen/assets/76956762/e14e193a-3f0f-4822-9c7d-f2a2019d738a)

**Comment by null2264** [comment]
Should be fixed in [v5.0.1 (Alpha 2)](https://github.com/null2264/CobbleGen/actions/runs/5298398019), it's still building tho... should take around 20mins

**Comment by null2264** [comment]
https://modrinth.com/mod/cobblegen/version/5.0.1+1.20.1b19-ALPHA-fabric
