### ISSUE TITLE
EMI unification

### ISSUE THREAD

**Issue by Disketaa** [null2264/CobbleGen#38]
Greetings! I switch REI to EMI and this mod have "World Interaction" category already. Looks mo' clear to me. Maybe it would possible to merge Basalt, Stone, Cobblestone categories into World Interaction one. 
![image](https://github.com/null2264/CobbleGen/assets/76956762/45fd87b0-a545-444b-9498-47bbd7f7989b)

Also maybe hide all the text like "Weight, Min Y, Dimension etc." and put them in tooltip when you hovering result item.

**Comment by null2264** [comment]
I was actually planning to do that, but I'm not sure if merging with other recipes is possible so I scrap the idea (at least for now).

**Comment by null2264** [comment]
But I'll look into it later today, they probably have something about this use-case somewhere in their documentation.

**Comment by null2264** [comment]
![image](https://github.com/null2264/CobbleGen/assets/46041660/3bebcba3-21a3-4ad8-83f3-0f3437f668f0)

**Comment by null2264** [comment]
It's added in v5.0.1

**Comment by Disketaa** [comment]
You're the best!
