### ISSUE TITLE
Can't seem to add new custom generators

### ISSUE THREAD

**Issue by KDFireHero** [null2264/CobbleGen#48]
I am trying to add three custom generators, one for andesite, one for diorite, and one for granite but it just refuses to translate into the game. Code:
                 "andesiteGen": {
			"minecraft:andesite": [
				{
					"id": "minecraft:andesite",
					"weight": 100.0
				}
			]
		},
		"dioriteGen": {
			"minecraft:diorite": [
				{
					"id": "minecraft:diorite",
					"weight": 100.0
				}
			]
		},
		"graniteGen": {
			"minecraft:granite": [
				{
					"id": "minecraft:granite",
					"weight": 100.0
				}
			]
		},

**Comment by null2264** [comment]
The xxxxGen is not meant to be the name of the generator, it's actually meant to be the **type** of the generator... if you want the generator to behave like regular ol' cobblegen (lava flowing into water from the side) use 'cobbleGen', if you want it to behave like stonegen (lava flowing into water from the top, or into still water) use 'stoneGen', or if you want it to behave like basaltgen (lava flowing into blue ice) then you use 'basaltGen'.

I'm assuming you want custom cobblegen that generate andesite, diorite, granite if generated block is on top of respective blocks... the config should look something like this:

```json5
"cobbleGen": {
  "minecraft:andesite": [
    {
      "id": "minecraft:andesite",
      "weight": 100.0
    }
  ],
  "minecraft:diorite": [
    {
      "id": "minecraft:diorite",
      "weight": 100.0
    }
  ],
  "minecraft:granite": [
    {
      "id": "minecraft:granite",
      "weight": 100.0
    }
  ]
},
```

**Comment by KDFireHero** [comment]
thank you
