### ISSUE TITLE
Incorrect order

### ISSUE THREAD

**Issue by Disketaa** [null2264/CobbleGen#51]
Hi! I found that one recipes have `WATER + LAVA > OUTPUT` order, others `LAVA + WATER > OUTPUT`

![image](https://github.com/null2264/CobbleGen/assets/76956762/068f23f8-06cd-419d-a05d-3398f505d7fe)

**Comment by null2264** [comment]
It's intended behavior, but I could add invert option...

**Comment by null2264** [comment]
It will be added in the next update
![image](https://github.com/null2264/CobbleGen/assets/46041660/c9b593fd-3a8e-4f79-8392-33129735a7ff)

**Comment by Disketaa** [comment]
you're the best
