### ISSUE TITLE
Error: Cant connect to server using CobbleGen

### ISSUE THREAD

**Issue by Ethereal-Sound** [null2264/CobbleGen#65]
Having issues connecting to a server modpack with an error returning from cobblegen:

![error](https://github.com/null2264/CobbleGen/assets/50870453/6110fa14-5cd7-4855-a08a-60cb4595753d)

No issues with the mod or modpack in Singleplayer, or with my existing config/custom generators. Annoyingly I can't find this line in my server logs but I can see it on my live readout, let me know if you require it and I can search further/try to recreate.

**Comment by BlueIsADude** [comment]
I'm having the same issue and i managed to stop it from disconnecting me, but i had to remove all of my advanced generators to connect. My theory is that the advanced generator template is currently outdated and needs to be updated, but i have no way of knowing for sure.

**Comment by null2264** [comment]
Did you enable experimentalFeatures on `cobblegen-meta.json5` by any chance? since I haven't test them extensively...

**Comment by BlueIsADude** [comment]
Nope. I hadnt updated cobblegen in a while though. the last version i used was 5.2.4, but i had to update to the latest update because of the new create update.

**Comment by null2264** [comment]
Interesting... I'll take a look later today.

**Comment by null2264** [comment]
While you're at it, can you provide the config that caused the disconnection issue? That'd be great, you can [email it to me](mailto:palembani@gmail.com) if it's private.

**Comment by BlueIsADude** [comment]
Sure, no problem, I'll send it right here.
Sorry if its a bit long!

```
{

	"cobbleGen": [
		{
			"id": "minecraft:cobblestone",
			"weight": 100.0,
			"minY": 0
		},
		{
			"id": "minecraft:cobbled_deepslate",
			"weight": 100.0,
			"maxY": 0
		}
	],
	"stoneGen": [
		{
			"id": "minecraft:stone",
			"weight": 100.0
		}
	],
	"basaltGen": [
		{
			"id": "minecraft:basalt",
			"weight": 100.0
		}
	],
	"customGen": {
		"cobbleGen": {
			"minecraft:crying_obsidian": [
				{
					"id": "randomium:randomium_ore",
					"weight": 0.5
				},
				{
					"id": "things:gleaming_ore",
					"weight": 2.0
				},
				{
					"id": "minecraft:emerald_ore",
					"weight": 1.0
				},
				{
					"id": "minecraft:diamond_ore",
					"weight": 3.0
				},
				{
					"id": "galosphere:silver_ore",
					"weight": 7.0
				},
				{
					"id": "minecraft:redstone_ore",
					"weight": 6.0
				},
				{
					"id": "minecraft:lapis_ore",
					"weight": 8.0
				},
				{
					"id": "minecraft:gold_ore",
					"weight": 10.0
				},
				{
					"id": "minecraft:iron_ore",
					"weight": 15.0
				},
				{
					"id": "create:zinc_ore",
					"weight": 20.0
				},
				{
					"id": "minecraft:copper_ore",
					"weight": 20.0
				},
				{
					"id": "minecraft:coal_ore",
					"weight": 25.0
				},
				{
					"id": "minecraft:cobblestone",
					"weight": 50.0
				}
			],
			"amarite:amarite_block": [
				{
					"id": "mythicupgrades:jade_ore",
					"weight": 0.5
				},
				{
					"id": "mythicupgrades:topaz_ore",
					"weight": 0.5
				},
				{
					"id": "mythicupgrades:aquamarine_ore",
					"weight": 0.5
				},
				{
					"id": "minecraft:cobblestone",
					"weight": 75.0
				}
			]
		},
		"stoneGen": {
			"minecraft:crying_obsidian": [
				{
					"id": "minecraft:stone",
					"weight": 40.0
				},
				{
					"id": "minecraft:diorite",
					"weight": 20.0
				},
				{
					"id": "minecraft:andesite",
					"weight": 20.0
				},
				{
					"id": "minecraft:granite",
					"weight": 20.0
				},
				{
					"id": "minecraft:tuff",
					"weight": 20.0
				},
				{
					"id": "create:asurine",
					"weight": 10.0
				},
				{
					"id": "create:crimsite",
					"weight": 10.0
				},
				{
					"id": "create:limestone",
					"weight": 10.0
				},
				{
					"id": "create:ochrum",
					"weight": 10.0
				},
				{
					"id": "create:veridium",
					"weight": 10.0
				},
				{
					"id": "create:scoria",
					"weight": 5.0
				},
				{
					"id": "create:scorchia",
					"weight": 5.0
				}
			]
		},
		"basaltGen": {
			"minecraft:crying_obsidian": [
				{
					"id": "minecraft:basalt",
					"weight": 50.0
				},
				{
					"id": "minecraft:nether_gold_ore",
					"weight": 10.0
				},
				{
					"id": "minecraft:nether_quartz_ore",
					"weight": 15.0
				},
				{
					"id": "minecraft:ancient_debris",
					"weight": 1.0
				}
			],
			"amarite:amarite_block": [
				{
					"id": "mythicupgrades:ruby_ore",
					"weight": 0.5
				},
				{
					"id": "mythicupgrades:sapphire_ore",
					"weight": 0.5
				},
				{
					"id": "minecraft:basalt",
					"weight": 75.0
				}
			]
		}
	},
	"advanced": {
		"create:honey": {
			"minecraft:water": {
				"results": {
					"*": [
						{
							"id": "minecraft:honey_block",
							"weight": 100.0
						}
					]
				}
			},
			"sliceanddice:fertilizer": {
				"results": {
					"*": [
						{
							"id": "minecraft:honeycomb_block",
							"weight": 100.0
						}
					]
				}
			}
		},
		"minecraft:lava": {
			"sliceanddice:fertilizer": {
				"results": {
					"*": [
						{
							"id": "minecraft:dirt",
							"weight": 100.0
						}
					],
					"minecraft:crying_obsidian": [
						{
							"id": "minecraft:dirt",
							"weight": 50.0
						},
						{
							"id": "minecraft:coarse_dirt",
							"weight": 30.0
						},
						{
							"id": "minecraft:rooted_dirt",
							"weight": 25.0
						},
						{
							"id": "farmersdelight:rich_soil",
							"weight": 5.0
						},
						{
							"id": "farmersdelight:organic_compost",
							"weight": 0.5
						}
					]
				}
			}
		},
		"minecraft:water": {
			"b:minecraft:magma_block": {
				"results": {
					"*": [
						{
							"id": "galosphere:pink_salt",
							"weight": 100.0
						}
					],
					"minecraft:soul_soil": [
						{
							"id": "galosphere:pink_salt",
							"weight": 33.3
						},
						{
							"id": "galosphere:rose_pink_salt",
							"weight": 33.3
						},
						{
							"id": "galosphere:pastel_pink_salt",
							"weight": 33.3
						}
					],
					"amarite:amarite_block": [
						{
							"id": "galosphere:pink_salt_straw",
							"weight": 75.0
						},
						{
							"id": "galosphere:pink_salt_cluster",
							"weight": 25.0
						}
					]
				}
			}
		}
	}
}
```

**Comment by null2264** [comment]
Lovely, thanks!

**Comment by Nathgon** [comment]
Heres my one as well for reference. It also exclusively using advanced generators;
`{
	"advanced": 
	{
		// Make sure to use still version of the fluid for this one,
		"minecraft:lava":
		{
			// replicates minecraft cobblestone and stone generator
			"minecraft:water":
				{
					// stone generator
					"resultsFromTop":
					{
						"*": [{"id": "minecraft:stone","weight": 1.0,}]
					},
					// cobblestone generator
					"results":
					{
						"*": [{"id": "minecraft:cobblestone","weight": 1.0,}]
					}
				},
			// replicates minecraft basalt generator
			"b:minecraft:blue_ice":
			{
				"results":
				{
					"minecraft:soul_soil": [{"id": "minecraft:basalt","weight": 1.0,}]
					"minecraft:bone_block": [{"id": "minecraft:calcite","weight": 1.0,}]
					"minecraft:magma_block": [{"id": "minecraft:blackstone","weight": 1.0,}]
					"minecraft:obsidian": [{"id": "minecraft:deepslate","weight": 1.0,}]
					"minecraft:crying_obsidian": [{"id": "minecraft:dripstone_block","weight": 1.0,}]
					"minecraft:red_sandstone": [{"id": "minecraft:granite","weight": 1.0,}]
					"minecraft:bedrock": [{"id": "minecraft:andesite", "weight": 1.0,"maxY": 0,}{"id": "minecraft:diorite", "weight": 1.0,"maxY": 0,}{"id": "minecraft:tuff", "weight": 1.0,"maxY": 0,}]
				}
			}
			"create_confectionery:caramel":
			{
				"results":
				{
					"minecraft:amethyst_block": [{"id": "create:asurine","weight": 1.0,}]
					"minecraft:dark_prismarine": [{"id": "create:veridium","weight": 1.0,}]
				}
			}
			"create_confectionery:white_chocolate":
			{
				"results":
				{
					"*": [{"id": "create:ochrum","weight":1.0}]
				}
			}
			"create_confectionery:black_chocolate":
			{
				"results":
				{
					"minecraft:soul_soil": [{"id": "create:crimsite","weight":1.0}]
					"minecraft:magma_block": [{"id": "create:scorchia","weight":1.0}]
				}
			}
			"create_confectionery:ruby_chocolate":
			{
				"results":
				{
					"create:andesite_alloy_block": [{"id": "minecraft:andesite","weight":1.0}]
					"minecraft:quartz_block": [{"id": "minecraft:diorite","weight":1.0}]
					"minecraft:gilded_blackstone": [{"id": "minecraft:tuff","weight":1.0}]
					"*":[{"id": "create:ochrum","weight":1.0}{"id": "create:scoria","weight":1.0}{"id": "create:asurine","weight": 1.0,}{"id": "create:veridium","weight": 1.0,}{"id": "create:crimsite","weight":1.0}{"id": "create:scorchia","weight":1.0}{"id": "create:limestone","weight":1.0}]
				}
			}
		}
		"create_confectionery:ruby_chocolate":
		{
			"b:minecraft:blue_ice":
			{
				"results":
				{
					"*": [{"id": "minecraft:granite","weight": 1.0,}{"id": "minecraft:dripstone_block","weight": 1.0,}{"id": "minecraft:deepslate","weight": 1.0,}{"id": "minecraft:blackstone","weight": 1.0,}{"id": "minecraft:calcite","weight": 1.0,}{"id": "minecraft:basalt","weight": 1.0,}{"id": "minecraft:andesite", "weight": 1.0,"maxY": 0,}{"id": "minecraft:diorite", "weight": 1.0,"maxY": 0,}{"id": "minecraft:tuff", "weight": 1.0,"maxY": 0,}]
				}
			}
		}
	}
}`

I can try and enable experimental features on the server when I get home tonight to see if that helps.

**Comment by Ethereal-Sound** [comment]
Here is my config for reference as well. I can try and enable experimental features when I get home tonight to see if that helps. It also uses exclusively advanced generators so...


	"advanced": 
	{
		// Make sure to use still version of the fluid for this one,
		"minecraft:lava":
		{
			// replicates minecraft cobblestone and stone generator
			"minecraft:water":
				{
					// stone generator
					"resultsFromTop":
					{
						"*": [{"id": "minecraft:stone","weight": 1.0,}]
					},
					// cobblestone generator
					"results":
					{
						"*": [{"id": "minecraft:cobblestone","weight": 1.0,}]
					}
				},
			// replicates minecraft basalt generator
			"b:minecraft:blue_ice":
			{
				"results":
				{
					"minecraft:soul_soil": [{"id": "minecraft:basalt","weight": 1.0,}]
					"minecraft:bone_block": [{"id": "minecraft:calcite","weight": 1.0,}]
					"minecraft:magma_block": [{"id": "minecraft:blackstone","weight": 1.0,}]
					"minecraft:obsidian": [{"id": "minecraft:deepslate","weight": 1.0,}]
					"minecraft:crying_obsidian": [{"id": "minecraft:dripstone_block","weight": 1.0,}]
					"minecraft:red_sandstone": [{"id": "minecraft:granite","weight": 1.0,}]
					"minecraft:bedrock": [{"id": "minecraft:andesite", "weight": 1.0,"maxY": 0,}{"id": "minecraft:diorite", "weight": 1.0,"maxY": 0,}{"id": "minecraft:tuff", "weight": 1.0,"maxY": 0,}]
				}
			}
			"create_confectionery:caramel":
			{
				"results":
				{
					"minecraft:amethyst_block": [{"id": "create:asurine","weight": 1.0,}]
					"minecraft:dark_prismarine": [{"id": "create:veridium","weight": 1.0,}]
				}
			}
			"create_confectionery:white_chocolate":
			{
				"results":
				{
					"*": [{"id": "create:ochrum","weight":1.0}]
				}
			}
			"create_confectionery:black_chocolate":
			{
				"results":
				{
					"minecraft:soul_soil": [{"id": "create:crimsite","weight":1.0}]
					"minecraft:magma_block": [{"id": "create:scorchia","weight":1.0}]
				}
			}
			"create_confectionery:ruby_chocolate":
			{
				"results":
				{
					"create:andesite_alloy_block": [{"id": "minecraft:andesite","weight":1.0}]
					"minecraft:quartz_block": [{"id": "minecraft:diorite","weight":1.0}]
					"minecraft:gilded_blackstone": [{"id": "minecraft:tuff","weight":1.0}]
					"*":[{"id": "create:ochrum","weight":1.0}{"id": "create:scoria","weight":1.0}{"id": "create:asurine","weight": 1.0,}{"id": "create:veridium","weight": 1.0,}{"id": "create:crimsite","weight":1.0}{"id": "create:scorchia","weight":1.0}{"id": "create:limestone","weight":1.0}]
				}
			}
		}
		"create_confectionery:ruby_chocolate":
		{
			"b:minecraft:blue_ice":
			{
				"results":
				{
					"*": [{"id": "minecraft:granite","weight": 1.0,}{"id": "minecraft:dripstone_block","weight": 1.0,}{"id": "minecraft:deepslate","weight": 1.0,}{"id": "minecraft:blackstone","weight": 1.0,}{"id": "minecraft:calcite","weight": 1.0,}{"id": "minecraft:basalt","weight": 1.0,}{"id": "minecraft:andesite", "weight": 1.0,"maxY": 0,}{"id": "minecraft:diorite", "weight": 1.0,"maxY": 0,}{"id": "minecraft:tuff", "weight": 1.0,"maxY": 0,}]
				}
			}
		}
	}

**Comment by null2264** [comment]
Try this build (build.tar.zst -> versions -> choose ur mc version and mod loader -> build -> libs -> choose the one without `-dev-shade` or `-sources`)

[build.zip](https://github.com/null2264/CobbleGen/files/14847939/build-artifacts.zip)

**Comment by Ethereal-Sound** [comment]
Sorry can we assume that I am a noob I don't quite understand what you want me to do with that zip

**Comment by null2264** [comment]
It contains a version of the mod with the potential fix for this bug.

**Comment by Ethereal-Sound** [comment]
Okay, sorry about that I haven't encountered tar.zst before, but I managed to get it into the server, and its fixed it! Can confirm that my generators are working and I was able to connect. 

Can also confirm that recipe viewing is also working for JEI.

**Comment by null2264** [comment]
Lovely, I'll release the fix to modrinth and curseforge after I test it on 24w14a.
