### ISSUE TITLE
Default basaltGen settings not appearing in JEI. 

### ISSUE THREAD

**Issue by deskydesqui** [null2264/CobbleGen#71]
### Steps to reproduce

1. Open recipe menu from JEI.
2. Go to Basalt Generation. 
3. There is no default basalt generation recipe. 

### Expected behavior

The default Soul Soil = Basalt recipe should appear, like default cobblestone and stone generation. 

### Actual behavior

No default recipe is seen. 

### Mod version

cobblegen-5.3.6+1.19.2b42-BETA-forge.jar

### Game version

1.19.2

### Modloader

Forge

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the mod to version **[5.3.4](https://github.com/null2264/CobbleGen/releases/latest)**.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Seems to be the same issue as GH-74, should be fixed in v5.3.9.
