### ISSUE TITLE
Basalt gen not working

### ISSUE THREAD

**Issue by d1vine-1** [null2264/CobbleGen#74]
### What happened?

My config for the basalt gen is not working, what did I do wrong? here is my code.
{
  "cobbleGen": [
    {
      "id": "minecraft:emerald_ore",
      "weight": 2.0
    },
    {
      "id": "minecraft:diamond_ore",
      "weight": 5.0
    },
    {
      "id": "minecraft:lapis_ore",
      "weight": 8.0
    },
    {
      "id": "minecraft:redstone_ore",
      "weight": 5.0
    },
    {
      "id": "minecraft:iron_ore",
      "weight": 15.0
    },
    {
      "id": "minecraft:coal_ore",
      "weight": 20.0
    },
    {
      "id": "minecraft:cobblestone",
      "weight": 45.0
    }
  ],
  "stoneGen": [
    {
      "id": "minecraft:stone",
      "weight": 100.0
    }
  ],
  "basaltGen": [
    {
      "id": "minecraft:stone",
      "weight": 100.0
    }
  ]
}

### Mod version

cobblegen-5.3.8+1.20.1b44-BETA-forge.jar

### Game version

1.20.1

### Modloader

Neoforge/Forge

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If I'm writing customGen configuration, I acknowledge that there are only 3 type of gens that exists which are `cobbleGen`, `stoneGen`, and `basaltGen`. Using any other type (such as `oreGen`) would cause it to stop working.
- [X] I have updated the mod to version **[5.3.8](https://github.com/null2264/CobbleGen/releases/latest)**.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Ah, it's never loaded... classic copy paste mistake, whoops...

Fixed on https://github.com/null2264/CobbleGen/commit/f133b11263a7f65264f83d2f6f0518b24c9f7cf5. I'll release the fix to Modrinth and CurseForge soon.
