### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [null2264/CobbleGen#75]
### Steps to reproduce

1. Run game with mod installed
2. Game crashes

### Expected behavior

The game should not crash on startup.

### Actual behavior

The game crashes on startup with this error:
`The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'cobblegen'!`

### Crash logs

[https://mclo.gs/tKzVxDH](https://mclo.gs/tKzVxDH)

### Mod version

cobblegen-5.2.4+1.19.4b33-BETA-fabric

### Game version

1.19.3

### Modloader

Fabric - 0.15.11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the mod to version **[5.3.9](https://github.com/null2264/CobbleGen/releases/latest)**.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Is it not possible for you to play on 1.20 or 1.19.2 instead? 1.19.3-1.19.4 are no longer supported (GH-47)...

**Comment by null2264** [comment]
Should be fixed on v5.3.13.
