### ISSUE TITLE
Cannot override obsidian generation / specify source block required

### ISSUE THREAD

**Issue by java-jambalaya** [null2264/CobbleGen#76]
### Steps to reproduce

I've attempted to override the creation of obsidian between lava and water using the following config:
```
"advanced": {
		"minecraft:lava": {
			"minecraft:water": {
				"results": {
					"*": [
						{
							"id": "minecraft:glass",
							"weight": 100.0,
						}
					]
				}
		    }
		}
	}
```
But cannot I get this behaviour, even by swapping the liquids around in the config.
Have I configured this incorrectly, is this a bug, or is this an unimplemented feature?

### Expected behavior

Where obsidian should generate, glass should instead.

### Actual behavior

Obsidian generates, and glass only generates in place of cobblestone.

### Mod version

5.3.9+1.20.1b45-BETA-forge

### Game version

1.20.1

### Modloader

Forge 47.2.17

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the mod to version **[5.3.9](https://github.com/null2264/CobbleGen/releases/latest)**.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
To override obsidian make sure you enabled experimental features in `cobblegen-meta.json5`, then instead of `results`, you use `obsidian`.

**Comment by java-jambalaya** [comment]
Thanks, that does it
