### ISSUE TITLE
Last custom generator in config file is the only one that works in-game

### ISSUE THREAD

**Issue by Zoophlas** [null2264/CobbleGen#77]
### What happened?

I've been tinkering with this for about an hour now and still can't figure out if I'm doing something wrong. Started trying to add in custom generators and at first I was able to get all of the ones I was adding (3 at the time) to all show up in REI and function correctly when tested. However after attempting to add one that uses copper blocks as the catalyst, and generate copper ore, deepslate copper ore, cobblestone, or cobbled deepslate, I've only been able to get the last entered generator working at any given point. I've tried different catalysts, tried to use different resulting products, retyped all of my generators, and even started from scratch using a different config file from a previous issue that had already been verified to be correct and no luck. Figured I post this here in-case I'm doing something wrong or in-case this is bug. I have included the config file in its original state when the problem first started. Any info/feedback would be appreciated. Thanks :)

https://drive.google.com/file/d/1tcvKBeT0zscWusb1J2MOpg-dJIn2F0ox/view?usp=sharing

### Mod version

5.3.9+1.20.1b45-BETA-fabric

### Game version

1.20.1

### Modloader

Fabric

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If I'm writing customGen configuration, I acknowledge that there are only 3 type of gens that exists which are `cobbleGen`, `stoneGen`, and `basaltGen`. Using any other type (such as `oreGen`) would cause it to stop working.
- [X] I have updated the mod to version **[5.3.9](https://github.com/null2264/CobbleGen/releases/latest)**.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
I can't access the file

![image](https://github.com/user-attachments/assets/09525231-20b9-4bb1-b7f2-b67a347cb247)

**Comment by Zoophlas** [comment]
I have changed the access to allow you to view it now, sorry about that!

**Comment by null2264** [comment]
You defined the custom (cobble) gen multiple times, you only need to do it once, if do it multiple times it'd just overwrite each other.

Before:
![image](https://github.com/user-attachments/assets/2f687bc5-7fe2-4f06-9306-5d9d662e10d3)

After merged:
![image](https://github.com/user-attachments/assets/a2cdc266-6c03-4a03-936c-e4ea4a195cfa)

As you can see above, you just need append a different modifier/catalyst instead of adding another `"cobbleGen": { ...`

**Comment by Zoophlas** [comment]
Perfect! Just made the changes and ofc everything works as expected, thank you very much!
