### ISSUE TITLE
No Config file is generated upon installation.

### ISSUE THREAD

**Issue by BeckPhillips** [null2264/CobbleGen#78]
### Steps to reproduce

Step one: Install the mod.
Step two: Look for the config file
Step three: make a config file
Step four: the config file doesn't work and I don't know if it's because I'm doing it wrong.

### Expected behavior

There should be a config file, with content inside that can be edited.

### Actual behavior

There is no config file, and I can't make one that works.

### Mod version

5.3.9+1.20.1b45-BETA-forge

### Game version

1.20.1

### Modloader

Forge

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have updated the mod to version **[5.3.9](https://github.com/null2264/CobbleGen/releases/latest)**.
- [X] I have filled out all of the requested information in this form.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.

**Comment by null2264** [comment]
It'll generate when you load a world without any config file, I'll force it to generate on game load on the next version
