### ISSUE TITLE
Crash when loading new chunks.

### ISSUE THREAD

**Issue by Spaaaaaaaace** [null2264/CobbleGen#8]
I have a personal server running the All of Fabric 5 modpack. I'm having an issue when new chunks are generated that happen to have water and lava interacting. The whole server dies and whenever the player who generated the chunk rejoins it crashes again. If I disable the mod on the server the player can rejoin and the issue goes away. I've attached some crash logs and my config file. Thanks for the mod, works excellent otherwise!
[cobblegen.json5.txt](https://github.com/null2264/CobbleGen/files/9193993/cobblegen.json5.txt)
[crash-2022-07-26_19.31.15-server.txt](https://github.com/null2264/CobbleGen/files/9193995/crash-2022-07-26_19.31.15-server.txt)
[crash-2022-07-26_19.33.55-server.txt](https://github.com/null2264/CobbleGen/files/9193996/crash-2022-07-26_19.33.55-server.txt)
[crash-2022-07-25_22.48.30-server.txt](https://github.com/null2264/CobbleGen/files/9193997/crash-2022-07-25_22.48.30-server.txt)

**Comment by null2264** [comment]
[cobblegen.zip](https://github.com/null2264/CobbleGen/files/9194175/cobblegen.zip)
Try this build, should fix this issue.

**Comment by Spaaaaaaaace** [comment]
I think I may have discovered the issue. Every block location in the crash logs is at y level 0. Looking at the config defaults that would be true for cobble and deepslate cobble instead of only one. 

Trying the new build now. No crashes yet, but it may need to generate a new chunk with lava and water at y=0 for a crash to occur. If changing the config and this build crashes I will reopen the issue.

**Comment by null2264** [comment]
![image](https://user-images.githubusercontent.com/46041660/181142345-098a5421-4d4c-4fd9-8922-bd198f7ebc88.png)
From my test, it's seems to be working now. I'll push the update to modrinth and curseforge soon.
