### ISSUE TITLE
Server and Client not connecting

### ISSUE THREAD

**Issue by Magor362** [null2264/CobbleGen#80]
### Steps to reproduce

- Installed a Neoforge Server with the neoforge installer
- downloaded my modpack, modified it for Server use (no client side mods, and a few server side ones).
    https://modrinth.com/modpack/weich-server-modpack (unlisted and not intended for public use)

- added custom cobblegen config, which does work (atleast in Fabric 1.21.1, both client and server)
- did start the server and (after other issues with unremoved client mods) started without major visible issues
- tried connecting with the client side of the modpack over localhost, but got the mentioned Issue

[error log about the connection](https://github.com/user-attachments/files/17397602/crash.log)

[modlist.txt](https://github.com/user-attachments/files/17397603/modlist.txt)

[Client side onscreen error message](https://github.com/user-attachments/assets/dca06826-c838-4a9d-9537-f3879f58b187)

### Expected behavior

connecting of the client to the server without an error

### Actual behavior

Error with message on Client:
Internal Exception: java.lang.UnsupportedOperationException: Payload cobblegen:ping_server may not be sent to the client!

### Crash logs

[latest.log](https://github.com/user-attachments/files/17397952/latest-log.log)

### Mod version

[NEOFORGE MC1.21+] v5.3.10-BETA

### Game version

1.21.1

### Modloader

NeoForge

### Other details

There is no problem connecting with cobblegen unlisted as a mod on the Server side

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the mod to version **[5.3.10](https://github.com/null2264/CobbleGen/releases/latest)**.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Sorry for the delay, finally got a time to debug, seems like NeoForge changed the way Minecraft handle networking on 1.20.x, I'll try to fix it ASAP.

**Comment by null2264** [comment]
Should be fixed in v5.3.12

**Comment by Magor362** [comment]
it works if installed both on Server and client, if only installed on the Server, this error comes up:
[disconnect-2024-11-04_01.06.06-client.txt](https://github.com/user-attachments/files/17612650/disconnect-2024-11-04_01.06.06-client.txt)

**Comment by null2264** [comment]
When you say "installed" you mean only the server got the updated mod (v5.3.12)?

Judging from the log, it seems like it is installed on client but not the updated version. I can't workaround it unfortunately since it's NeoForge internal's behaviour, so client also need to update the mod...

**Comment by Magor362** [comment]
you are right, i forgot the old installation because of the cryptic old name. 

It works now with no version installed on the client flawlessly

**Comment by null2264** [comment]
Yeah, I messed up the filename on v5.3.10.

Glad that it's fixed now 👍
